#!/usr/bin/env bash
# scripts/zitadel-setup.sh — everything Argo CD needs on the ZITADEL side, through ZITADEL's API:
#   project "argocd" with roles platform-admins / product-developers / platform-viewers
#   an OIDC web app for the UI (client ID + secret are generated by ZITADEL, so they can't live in Git upfront)
#   a second, public OIDC app for the argocd CLI (no secret, PKCE); Argo CD hands its ID to the CLI as cliClientID
#   the "groupsClaim" Action: ZITADEL puts roles in urn:zitadel:iam:org:project:roles, Argo CD wants "groups"
#   three users, alice (platform-admins), dave (product-developers) and bob (platform-viewers)
#   clientID, clientSecret and cliClientID in Vault at secret/platform/argocd/oidc-zitadel; the ExternalSecret
#   argocd/argocd-oidc-zitadel (platform-gitops blog-05b) turns them into the Secret oidc.config reads.
#   In blog-05 this script wrote that Secret itself; that was the one secret never in Git.
# It authenticates with the PAT the chart's setup job wrote to the Secret zitadel/iam-admin-pat.
# Safe to re-run: existing objects are looked up by name and reused.
set -euo pipefail
Z=${ZITADEL_URL:-http://zitadel.127.0.0.1.nip.io:8081}
ARGOCD_URL=${ARGOCD_URL:-http://localhost:8080}
PASSWORD=${LAB_PASSWORD:-Password1!}
PAT=$(kubectl -n zitadel get secret iam-admin-pat -o jsonpath='{.data.pat}' | base64 -d)
VAULT_TOKEN=$(jq -r .root_token "$(dirname "$0")/../.lab/vault-init.json")
v() { kubectl -n vault exec -i vault-0 -- env VAULT_TOKEN="$VAULT_TOKEN" vault "$@"; }
api() { curl -sS --fail-with-body -H "Authorization: Bearer $PAT" -H 'Content-Type: application/json' -X "$1" "$Z$2" ${3:+-d "$3"}; }
jqr() { python3 -c "import sys,json; d=json.load(sys.stdin); print($1)"; }

# 1. project + roles. projectRoleAssertion puts the roles into tokens,
#    projectRoleCheck refuses login to users without any role on the project.
project=$(api POST /management/v1/projects/_search '{"queries":[{"nameQuery":{"name":"argocd","method":"TEXT_QUERY_METHOD_EQUALS"}}]}' | jqr "(d.get('result') or [{}])[0].get('id','')")
if [ -z "$project" ]; then
  project=$(api POST /management/v1/projects '{"name":"argocd","projectRoleAssertion":true,"projectRoleCheck":true}' | jqr "d['id']")
  api POST "/management/v1/projects/$project/roles/_bulk" \
    '{"roles":[{"key":"platform-admins","displayName":"Platform admins"},{"key":"platform-viewers","displayName":"Platform viewers"}]}' >/dev/null
fi
# product-developers came later; added on its own so a project created by an older run gets it too.
roles=$(api POST "/management/v1/projects/$project/roles/_search" '{}' | jqr "' '.join(r['key'] for r in d.get('result',[]))")
case " $roles " in *" product-developers "*) ;; *)
  api POST "/management/v1/projects/$project/roles" '{"roleKey":"product-developers","displayName":"Product developers"}' >/dev/null ;;
esac
echo "project argocd: $project"

# 2. OIDC app for the UI. devMode allows the http:// redirect URI of the lab; production uses https and devMode false.
app=$(api POST "/management/v1/projects/$project/apps/_search" '{"queries":[{"nameQuery":{"name":"argocd","method":"TEXT_QUERY_METHOD_EQUALS"}}]}' | jqr "(d.get('result') or [{}])[0].get('id','')")
if [ -z "$app" ]; then
  out=$(api POST "/management/v1/projects/$project/apps/oidc" "{
    \"name\": \"argocd\",
    \"redirectUris\": [\"$ARGOCD_URL/auth/callback\"],
    \"postLogoutRedirectUris\": [\"$ARGOCD_URL\"],
    \"responseTypes\": [\"OIDC_RESPONSE_TYPE_CODE\"],
    \"grantTypes\": [\"OIDC_GRANT_TYPE_AUTHORIZATION_CODE\"],
    \"appType\": \"OIDC_APP_TYPE_WEB\",
    \"authMethodType\": \"OIDC_AUTH_METHOD_TYPE_BASIC\",
    \"devMode\": true,
    \"idTokenRoleAssertion\": true,
    \"idTokenUserinfoAssertion\": true,
    \"accessTokenRoleAssertion\": true
  }")
  client_id=$(echo "$out" | jqr "d['clientId']"); client_secret=$(echo "$out" | jqr "d['clientSecret']")
  # put, not patch: this is the first write and creates the path. Every later change is a patch.
  v kv put secret/platform/argocd/oidc-zitadel clientID="$client_id" clientSecret="$client_secret" >/dev/null
  echo "app argocd: client $client_id, secret written to Vault secret/platform/argocd/oidc-zitadel"
else
  echo "app argocd: exists ($app), keeping secret/platform/argocd/oidc-zitadel"
fi

# 2b. OIDC app for the CLI. `argocd login --sso` is a public client: it can't keep a secret, so it uses PKCE and
#     a local callback on localhost:8085. With the UI app's client ID, ZITADEL answers
#     'invalid_client "empty client secret"'. A native app with auth method NONE is what the CLI can use.
cli_app=$(api POST "/management/v1/projects/$project/apps/_search" '{"queries":[{"nameQuery":{"name":"argocd-cli","method":"TEXT_QUERY_METHOD_EQUALS"}}]}' | jqr "(d.get('result') or [{}])[0].get('oidcConfig',{}).get('clientId','')")
if [ -z "$cli_app" ]; then
  cli_app=$(api POST "/management/v1/projects/$project/apps/oidc" '{
    "name": "argocd-cli",
    "redirectUris": ["http://localhost:8085/auth/callback"],
    "responseTypes": ["OIDC_RESPONSE_TYPE_CODE"],
    "grantTypes": ["OIDC_GRANT_TYPE_AUTHORIZATION_CODE", "OIDC_GRANT_TYPE_REFRESH_TOKEN"],
    "appType": "OIDC_APP_TYPE_NATIVE",
    "authMethodType": "OIDC_AUTH_METHOD_TYPE_NONE",
    "devMode": true,
    "idTokenRoleAssertion": true,
    "idTokenUserinfoAssertion": true,
    "accessTokenRoleAssertion": true
  }' | jqr "d['clientId']")
fi
v kv patch secret/platform/argocd/oidc-zitadel cliClientID="$cli_app" >/dev/null
kubectl -n argocd annotate es argocd-oidc-zitadel force-sync="$(date +%s)" --overwrite >/dev/null
echo "app argocd-cli: client $cli_app (public, PKCE), written to Vault as cliClientID"

# 3. groups claim. Actions v1 (inline JavaScript); deprecated in ZITADEL v4, removed in v5.
#    Flow type 2 = Complement Token; triggers 4 = pre userinfo creation, 5 = pre access token creation.
action=$(api POST /management/v1/actions/_search '{"queries":[{"actionNameQuery":{"name":"groupsClaim","method":"TEXT_QUERY_METHOD_EQUALS"}}]}' | jqr "(d.get('result') or [{}])[0].get('id','')")
if [ -z "$action" ]; then
  script='function groupsClaim(ctx, api) {
  if (ctx.v1.user.grants === undefined || ctx.v1.user.grants.count == 0) { return; }
  let groups = [];
  ctx.v1.user.grants.grants.forEach(g => { g.roles.forEach(r => { groups.push(r); }); });
  api.v1.claims.setClaim("groups", groups);
}'
  body=$(python3 -c 'import json,sys; print(json.dumps({"name":"groupsClaim","script":sys.argv[1],"timeout":"10s","allowedToFail":True}))' "$script")
  action=$(api POST /management/v1/actions "$body" | jqr "d['id']")
  for trigger in 4 5; do api POST "/management/v1/flows/2/trigger/$trigger" "{\"actionIds\":[\"$action\"]}" >/dev/null; done
fi
echo "action groupsClaim: $action"

# 4. users and role grants
user() { # user <username> <given> <role>
  id=$(api POST /v2/users '{"queries":[{"userNameQuery":{"userName":"'"$1"'","method":"TEXT_QUERY_METHOD_EQUALS"}}]}' | jqr "(d.get('result') or [{}])[0].get('userId','')")
  if [ -z "$id" ]; then
    id=$(api POST /v2/users/human "{
      \"username\": \"$1\",
      \"profile\": {\"givenName\": \"$2\", \"familyName\": \"Lab\"},
      \"email\": {\"email\": \"$1@lab.example\", \"isVerified\": true},
      \"password\": {\"password\": \"$PASSWORD\", \"changeRequired\": false}
    }" | jqr "d['userId']")
    api POST "/management/v1/users/$id/grants" "{\"projectId\":\"$project\",\"roleKeys\":[\"$3\"]}" >/dev/null
  fi
  echo "user $1 ($3): $id"
}
user alice Alice platform-admins
user dave Dave product-developers
user bob Bob platform-viewers
