repos:
  # General checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: detect-private-key

  - repo: https://github.com/miraccan00/blog-wiki
    rev: pre-commit-ozel-kontroller  # git tag veya commit hash kullanın
    hooks:
      - id: repository-validation
      - id: trivy-fs-scan

  # Go formatting and checks (Windows compatible)
  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt test
        entry: go fmt ./...
        language: system
        types: [go]
        pass_filenames: false

      - id: go-mod-tidy
        name: go mod tidy
        entry: go mod tidy
        language: system
        types: [go]
        pass_filenames: false
      - id: go-build
        name: go build
        entry: go build ./...
        language: system
        types: [go]
        pass_filenames: false
