#!/usr/bin/env bash
# scripts/zitadel-setup.sh — everything Argo CD needs on the ZITADEL side, through ZITADEL's API:
#   project "argocd" with roles platform-admins / platform-viewers
#   an OIDC web app (client ID + secret are generated by ZITADEL, so they can't live in Git upfront)
#   the "groupsClaim" Action: ZITADEL puts roles in urn:zitadel:iam:org:project:roles, Argo CD wants "groups"
#   two users, alice (platform-admins) and bob (platform-viewers)
#   the Secret argocd-oidc-zitadel in argocd, which oidc.config reads as $argocd-oidc-zitadel:clientID/clientSecret
# It authenticates with the PAT the chart's setup job wrote to the Secret zitadel/iam-admin-pat.
# Safe to re-run: existing objects are looked up by name and reused.
set -euo pipefail
Z=${ZITADEL_URL:-http://zitadel.127.0.0.1.nip.io:8081}
ARGOCD_URL=${ARGOCD_URL:-http://localhost:8080}
PASSWORD=${LAB_PASSWORD:-Password1!}
PAT=$(kubectl -n zitadel get secret iam-admin-pat -o jsonpath='{.data.pat}' | base64 -d)
api() { curl -sS --fail-with-body -H "Authorization: Bearer $PAT" -H 'Content-Type: application/json' -X "$1" "$Z$2" ${3:+-d "$3"}; }
jqr() { python3 -c "import sys,json; d=json.load(sys.stdin); print($1)"; }

# 1. project + roles. projectRoleAssertion puts the roles into tokens,
#    projectRoleCheck refuses login to users without any role on the project.
project=$(api POST /management/v1/projects/_search '{"queries":[{"nameQuery":{"name":"argocd","method":"TEXT_QUERY_METHOD_EQUALS"}}]}' | jqr "(d.get('result') or [{}])[0].get('id','')")
if [ -z "$project" ]; then
  project=$(api POST /management/v1/projects '{"name":"argocd","projectRoleAssertion":true,"projectRoleCheck":true}' | jqr "d['id']")
  api POST "/management/v1/projects/$project/roles/_bulk" \
    '{"roles":[{"key":"platform-admins","displayName":"Platform admins"},{"key":"platform-viewers","displayName":"Platform viewers"}]}' >/dev/null
fi
echo "project argocd: $project"

# 2. OIDC app. devMode allows the http:// redirect URIs of the lab; production uses https and devMode false.
#    Two redirect URIs: the UI, and localhost:8085 for `argocd login --sso` from the CLI.
app=$(api POST "/management/v1/projects/$project/apps/_search" '{"queries":[{"nameQuery":{"name":"argocd","method":"TEXT_QUERY_METHOD_EQUALS"}}]}' | jqr "(d.get('result') or [{}])[0].get('id','')")
if [ -z "$app" ]; then
  out=$(api POST "/management/v1/projects/$project/apps/oidc" "{
    \"name\": \"argocd\",
    \"redirectUris\": [\"$ARGOCD_URL/auth/callback\", \"http://localhost:8085/auth/callback\"],
    \"postLogoutRedirectUris\": [\"$ARGOCD_URL\"],
    \"responseTypes\": [\"OIDC_RESPONSE_TYPE_CODE\"],
    \"grantTypes\": [\"OIDC_GRANT_TYPE_AUTHORIZATION_CODE\"],
    \"appType\": \"OIDC_APP_TYPE_WEB\",
    \"authMethodType\": \"OIDC_AUTH_METHOD_TYPE_BASIC\",
    \"devMode\": true,
    \"idTokenRoleAssertion\": true,
    \"idTokenUserinfoAssertion\": true,
    \"accessTokenRoleAssertion\": true
  }")
  client_id=$(echo "$out" | jqr "d['clientId']"); client_secret=$(echo "$out" | jqr "d['clientSecret']")
  kubectl -n argocd create secret generic argocd-oidc-zitadel \
    --from-literal=clientID="$client_id" --from-literal=clientSecret="$client_secret" \
    --dry-run=client -o yaml | kubectl label -f - --local -o yaml app.kubernetes.io/part-of=argocd | kubectl apply -f - >/dev/null
  echo "app argocd: client $client_id, secret written to argocd/argocd-oidc-zitadel"
else
  echo "app argocd: exists ($app), keeping argocd/argocd-oidc-zitadel"
fi

# 3. groups claim. Actions v1 (inline JavaScript); deprecated in ZITADEL v4, removed in v5.
#    Flow type 2 = Complement Token; triggers 4 = pre userinfo creation, 5 = pre access token creation.
action=$(api POST /management/v1/actions/_search '{"queries":[{"actionNameQuery":{"name":"groupsClaim","method":"TEXT_QUERY_METHOD_EQUALS"}}]}' | jqr "(d.get('result') or [{}])[0].get('id','')")
if [ -z "$action" ]; then
  script='function groupsClaim(ctx, api) {
  if (ctx.v1.user.grants === undefined || ctx.v1.user.grants.count == 0) { return; }
  let groups = [];
  ctx.v1.user.grants.grants.forEach(g => { g.roles.forEach(r => { groups.push(r); }); });
  api.v1.claims.setClaim("groups", groups);
}'
  body=$(python3 -c 'import json,sys; print(json.dumps({"name":"groupsClaim","script":sys.argv[1],"timeout":"10s","allowedToFail":True}))' "$script")
  action=$(api POST /management/v1/actions "$body" | jqr "d['id']")
  for trigger in 4 5; do api POST "/management/v1/flows/2/trigger/$trigger" "{\"actionIds\":[\"$action\"]}" >/dev/null; done
fi
echo "action groupsClaim: $action"

# 4. users and role grants
user() { # user <username> <given> <role>
  id=$(api POST /v2/users '{"queries":[{"userNameQuery":{"userName":"'"$1"'","method":"TEXT_QUERY_METHOD_EQUALS"}}]}' | jqr "(d.get('result') or [{}])[0].get('userId','')")
  if [ -z "$id" ]; then
    id=$(api POST /v2/users/human "{
      \"username\": \"$1\",
      \"profile\": {\"givenName\": \"$2\", \"familyName\": \"Lab\"},
      \"email\": {\"email\": \"$1@lab.example\", \"isVerified\": true},
      \"password\": {\"password\": \"$PASSWORD\", \"changeRequired\": false}
    }" | jqr "d['userId']")
    api POST "/management/v1/users/$id/grants" "{\"projectId\":\"$project\",\"roleKeys\":[\"$3\"]}" >/dev/null
  fi
  echo "user $1 ($3): $id"
}
user alice Alice platform-admins
user bob Bob platform-viewers
